{ pkgs, iconTheme, ... }:
let
  dotfiles = ../dotfiles;

  mkFiles = prefix: paths:
    builtins.listToAttrs (map (p: {
      name = "${prefix}/${p}";
      value = { source = dotfiles + "/${prefix}/${p}"; };
    }) paths);

  # Matugen config with all Numix icon theme references replaced by the nix-declared theme.
  # The source dotfiles are left untouched; this derivation produces the substituted version.
  matugenConfig = pkgs.runCommand "matugen-config" {} ''
    cp -r ${../dotfiles/matugen} $out
    chmod -R u+w $out
    find $out -type f -exec sed -i \
      -e 's/Numix-Circle-Light/${iconTheme.name}/g' \
      -e 's/Numix-Circle/${iconTheme.name}/g' \
      {} \;
  '';
in
{
  xdg.configFile =
    mkFiles "hypr" [
      "hyprland.conf"
      "workspaces.conf"
      "hypridle.conf"
      "hyprlock.conf"
      "components/animations.conf"
      "components/binds.conf"
      "components/devices.conf"
      "components/layouts.conf"
      "components/lookandfeel.conf"
      "components/windowrules.conf"
      "icons/dwindle.svg"
      "icons/master.svg"
      "icons/monocle.svg"
      "icons/scrolling.svg"
      "scripts/cheatsheet.sh"
      "scripts/code-launcher.sh"
      "scripts/color-picker.sh"
      "scripts/dispatch-terminals.sh"
      "scripts/drawer.sh"
      "scripts/layout-switch.sh"
      "scripts/nvim.sh"
      "scripts/reload-styles.sh"
      "scripts/restore-wallpaper.sh"
      "scripts/take-screenshot.sh"
      "scripts/take-static-screenshot.sh"
    ]
    // mkFiles "waybar" [
      "style.css"
      "config_horizontal.jsonc"
      "config_vertical.jsonc"
      "is_vertical"
      "launch-waybar.sh"
      "scripts/battery-status.sh"
      "scripts/disk.sh"
      "scripts/ime-status.sh"
      "scripts/ime-switch.sh"
      "scripts/memory-gpu.sh"
      "scripts/vscode-apply-colors.sh"
      "scripts/wallpaper-selector.sh"
      "scripts/weather.sh"
      "scripts/workspace-scroll.sh"
    ]
    // mkFiles "walker" [
      "config.toml"
      "style.css"
      "themes/colorpicker/layout.xml"
      "themes/colorpicker/style.css"
      "themes/grid-actions/layout.xml"
      "themes/grid-actions/style.css"
      "themes/matugen/style.css"
    ]
    // mkFiles "swaync" [
      "config.json"
      "style.css"
    ]
    // mkFiles "fcitx5" [
      "config"
      "profile"
      "conf/classicui.conf"
      "conf/pinyin.conf"
      "conf/chttrans.conf"
      "conf/punctuation.conf"
      "conf/notifications.conf"
    ]
    // {
      "swayosd/style.css".source = dotfiles + "/swayosd/style.css";
      "kitty/kitty.conf".source = dotfiles + "/kitty/kitty.conf";
      "imv/config".source = dotfiles + "/imv/config";
      "mpv/scripts/osc.lua".source = dotfiles + "/mpv/scripts/osc.lua";
      # elephant config — read-only lua scripts and data, no color files
      "elephant".source = dotfiles + "/elephant";
      # matugen — nix-derived copy with icon theme substituted
      "matugen".source = matugenConfig;

      # env.conf — generated by nix; removes arch-specific XDG_MENU_PREFIX,
      # fixes cursor to what's installed, deduplicates from environment.variables
      "hypr/components/env.conf".text = ''
        env = XCURSOR_SIZE, 24
        env = HYPRCURSOR_SIZE, 24
        env = XCURSOR_THEME, breeze_cursors
        env = HYPRCURSOR_THEME, breeze_cursors
        env = QT_QPA_PLATFORMTHEME, qt6ct
        env = GTK_THEME, adw-gtk3-dark
        env = GTK_TOOLTIP_TIMEOUT, 0
        env = XDG_CURRENT_DESKTOP, Hyprland
        env = XDG_SESSION_DESKTOP, Hyprland
        env = XDG_SESSION_TYPE, wayland
      '';

      # autostart.conf — generated by nix; fixes polkit path, sets icon theme from nix variable
      "hypr/components/autostart.conf".text = ''
        exec-once = xsettingsd
        exec-once = hyprlock
        exec-once = swaync
        exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
        exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
        exec-once = gsettings set org.gnome.desktop.interface icon-theme '${iconTheme.name}'
        exec-once = fcitx5 -d --replace
        exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP GTK_THEME
        exec-once = ${pkgs.polkit_gnome}/libexec/polkit-gnome-authentication-agent-1
        exec-once = hypridle
        exec-once = elephant
        exec-once = walker --gapplication-service
        exec-once = swayosd-server
        exec-once = sh -c "~/.config/waybar/launch-waybar.sh"

        # workspace 1: terminals
        exec-once = ~/.config/hypr/scripts/dispatch-terminals.sh
        windowrule = workspace 1 silent, match:class ^(kitty-main)$
        windowrule = workspace 1 silent, match:class ^(kitty-btop)$
        windowrule = workspace 1 silent, match:class ^(kitty-yazi)$

        # workspace 3: browser
        exec-once = zen-browser
        windowrule = workspace 3 silent, match:class ^(zen)$

        # workspace 11-12 (second screen): discord, feishin, steam
        exec-once = firejail --net=eth0 --dns=1.1.1.1 --noprofile vesktop --enable-features=UseOzonePlatform --ozone-platform=wayland
        exec-once = feishin
        exec-once = steam
        windowrule = workspace 11 silent, match:class ^(vesktop)$
        windowrule = workspace 11 silent, match:class ^(feishin)$
        windowrule = workspace 12 silent, match:class ^(steam)$

        # wallpaper
        exec-once = awww-daemon
        exec-once = ~/.config/hypr/scripts/restore-wallpaper.sh
      '';
    };

  programs.mpv = {
    enable = true;
    scripts = [ pkgs.mpvScripts.thumbfast ];
  };
}
