cursor #a6accd
cursor_text_color #8f93a2

foreground            #a6accd
background            #090b10
selection_foreground  #0f111a
selection_background  #c792ea
url_color             #82aaff

# black
color0   #292d3e
color8   #464b5d

# red (secondary, hue forced to red)
color1   #ff5370
color9   #f07178

# green (tertiary, hue forced to green)
color2   #c3e88d
color10  #c3e88d

# yellow (primary, hue forced to yellow)
color3   #ffcb6b
color11  #ffcb6b

# blue (primary, as-is)
color4   #82aaff
color12  #82aaff

# magenta (secondary, hue forced to magenta)
color5   #c792ea
color13  #c792ea

# cyan (tertiary, hue forced to cyan)
color6   #89ddff
color14  #89ddff

# white
color7   #8f93a2
color15  #eeffff

mark1_foreground #0f111a
mark1_background #89ddff
mark2_foreground #0f111a
mark2_background #89ddff
mark3_foreground #0f111a
mark3_background #ffcb6b

active_tab_foreground #0f111a
active_tab_background #82aaff
inactive_tab_foreground #0f111a
inactive_tab_background #89ddff

active_border_color #82aaff
inactive_border_color #0f111a
