
$image = Null
$background = rgba(181616ff)

$image = Null
$error = rgba(c4746eff)

$image = Null
$error_container = rgba(e46876ff)

$image = Null
$inverse_on_surface = rgba(181616ff)

$image = Null
$inverse_primary = rgba(7fb4caff)

$image = Null
$inverse_surface = rgba(9e9b93ff)

$image = Null
$on_background = rgba(c5c9c5ff)

$image = Null
$on_error = rgba(181616ff)

$image = Null
$on_error_container = rgba(181616ff)

$image = Null
$on_primary = rgba(181616ff)

$image = Null
$on_primary_container = rgba(181616ff)

$image = Null
$on_primary_fixed = rgba(181616ff)

$image = Null
$on_primary_fixed_variant = rgba(282727ff)

$image = Null
$on_secondary = rgba(181616ff)

$image = Null
$on_secondary_container = rgba(181616ff)

$image = Null
$on_secondary_fixed = rgba(181616ff)

$image = Null
$on_secondary_fixed_variant = rgba(282727ff)

$image = Null
$on_surface = rgba(c5c9c5ff)

$image = Null
$on_surface_variant = rgba(a6a69cff)

$image = Null
$on_tertiary = rgba(181616ff)

$image = Null
$on_tertiary_container = rgba(181616ff)

$image = Null
$on_tertiary_fixed = rgba(181616ff)

$image = Null
$on_tertiary_fixed_variant = rgba(282727ff)

$image = Null
$outline = rgba(7a8382ff)

$image = Null
$outline_variant = rgba(625e5aff)

$image = Null
$primary = rgba(957fb8ff)

$image = Null
$primary_container = rgba(8992a7ff)

$image = Null
$primary_fixed = rgba(8992a7ff)

$image = Null
$primary_fixed_dim = rgba(957fb8ff)

$image = Null
$scrim = rgba(000000ff)

$image = Null
$secondary = rgba(8ba4b0ff)

$image = Null
$secondary_container = rgba(7fb4caff)

$image = Null
$secondary_fixed = rgba(7fb4caff)

$image = Null
$secondary_fixed_dim = rgba(8ba4b0ff)

$image = Null
$shadow = rgba(000000ff)

$image = Null
$source_color = rgba(957fb8ff)

$image = Null
$surface = rgba(181616ff)

$image = Null
$surface_bright = rgba(625e5aff)

$image = Null
$surface_container = rgba(282727ff)

$image = Null
$surface_container_high = rgba(393836ff)

$image = Null
$surface_container_highest = rgba(625e5aff)

$image = Null
$surface_container_low = rgba(1d1c19ff)

$image = Null
$surface_container_lowest = rgba(0d0c0cff)

$image = Null
$surface_dim = rgba(12120fff)

$image = Null
$surface_tint = rgba(957fb8ff)

$image = Null
$surface_variant = rgba(625e5aff)

$image = Null
$tertiary = rgba(87a987ff)

$image = Null
$tertiary_container = rgba(8a9a7bff)

$image = Null
$tertiary_fixed = rgba(8a9a7bff)

$image = Null
$tertiary_fixed_dim = rgba(87a987ff)
