cursor #c5c9c5
cursor_text_color #a6a69c

foreground            #c5c9c5
background            #0d0c0c
selection_foreground  #181616
selection_background  #8ba4b0
url_color             #957fb8

# black
color0   #393836
color8   #625e5a

# red (secondary, hue forced to red)
color1   #c4746e
color9   #e46876

# green (tertiary, hue forced to green)
color2   #8a9a7b
color10  #87a987

# yellow (primary, hue forced to yellow)
color3   #c4b28a
color11  #e6c384

# blue (primary, as-is)
color4   #8ba4b0
color12  #7fb4ca

# magenta (secondary, hue forced to magenta)
color5   #a292a3
color13  #938aa9

# cyan (tertiary, hue forced to cyan)
color6   #8ea4a2
color14  #7aa89f

# white
color7   #9e9b93
color15  #c5c9c5

mark1_foreground #181616
mark1_background #8992a7
mark2_foreground #181616
mark2_background #7fb4ca
mark3_foreground #181616
mark3_background #8a9a7b

active_tab_foreground #181616
active_tab_background #957fb8
inactive_tab_foreground #181616
inactive_tab_background #8992a7

active_border_color #957fb8
inactive_border_color #181616
