
$image = Null
$background = rgba(1e1e2eff)

$image = Null
$error = rgba(f38ba8ff)

$image = Null
$error_container = rgba(eba0acff)

$image = Null
$inverse_on_surface = rgba(1e1e2eff)

$image = Null
$inverse_primary = rgba(b4befeff)

$image = Null
$inverse_surface = rgba(a6adc8ff)

$image = Null
$on_background = rgba(cdd6f4ff)

$image = Null
$on_error = rgba(1e1e2eff)

$image = Null
$on_error_container = rgba(1e1e2eff)

$image = Null
$on_primary = rgba(1e1e2eff)

$image = Null
$on_primary_container = rgba(1e1e2eff)

$image = Null
$on_primary_fixed = rgba(1e1e2eff)

$image = Null
$on_primary_fixed_variant = rgba(313244ff)

$image = Null
$on_secondary = rgba(1e1e2eff)

$image = Null
$on_secondary_container = rgba(1e1e2eff)

$image = Null
$on_secondary_fixed = rgba(1e1e2eff)

$image = Null
$on_secondary_fixed_variant = rgba(313244ff)

$image = Null
$on_surface = rgba(cdd6f4ff)

$image = Null
$on_surface_variant = rgba(bac2deff)

$image = Null
$on_tertiary = rgba(1e1e2eff)

$image = Null
$on_tertiary_container = rgba(1e1e2eff)

$image = Null
$on_tertiary_fixed = rgba(1e1e2eff)

$image = Null
$on_tertiary_fixed_variant = rgba(313244ff)

$image = Null
$outline = rgba(6c7086ff)

$image = Null
$outline_variant = rgba(585b70ff)

$image = Null
$primary = rgba(cba6f7ff)

$image = Null
$primary_container = rgba(f5c2e7ff)

$image = Null
$primary_fixed = rgba(f5c2e7ff)

$image = Null
$primary_fixed_dim = rgba(cba6f7ff)

$image = Null
$scrim = rgba(000000ff)

$image = Null
$secondary = rgba(89b4faff)

$image = Null
$secondary_container = rgba(74c7ecff)

$image = Null
$secondary_fixed = rgba(74c7ecff)

$image = Null
$secondary_fixed_dim = rgba(89b4faff)

$image = Null
$shadow = rgba(000000ff)

$image = Null
$source_color = rgba(cba6f7ff)

$image = Null
$surface = rgba(1e1e2eff)

$image = Null
$surface_bright = rgba(6c7086ff)

$image = Null
$surface_container = rgba(313244ff)

$image = Null
$surface_container_high = rgba(45475aff)

$image = Null
$surface_container_highest = rgba(585b70ff)

$image = Null
$surface_container_low = rgba(1e1e2eff)

$image = Null
$surface_container_lowest = rgba(11111bff)

$image = Null
$surface_dim = rgba(181825ff)

$image = Null
$surface_tint = rgba(cba6f7ff)

$image = Null
$surface_variant = rgba(585b70ff)

$image = Null
$tertiary = rgba(94e2d5ff)

$image = Null
$tertiary_container = rgba(a6e3a1ff)

$image = Null
$tertiary_fixed = rgba(a6e3a1ff)

$image = Null
$tertiary_fixed_dim = rgba(94e2d5ff)
