-- Auto-generated by Matugen
-- Colors derived from matugen palette with forced hues (matching ANSI/kitty)

local colors = {
  red      = '#f38ba8',
  green    = '#a6e3a1',
  yellow   = '#f9e2af',
  blue     = '#89b4fa',
  magenta  = '#cba6f7',
  cyan     = '#94e2d5',
  orange   = '#fab387',
  pink     = '#f5c2e7',

  fg       = '#cdd6f4',
  fg_dim   = '#bac2de',
  comment  = '#6c7086',
  primary  = '#cba6f7',
  secondary = '#89b4fa',
}

-- Helper
local function set_hl_multiple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Core: transparent backgrounds
vim.api.nvim_set_hl(0, 'Normal', { fg = colors.fg, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'NormalNC', { fg = colors.fg, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = colors.fg, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'SignColumn', { bg = 'NONE' })
vim.api.nvim_set_hl(0, 'EndOfBuffer', { fg = colors.comment, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'MsgArea', { fg = colors.fg, bg = 'NONE' })

-- Selection / cursor (these need bg to be readable)
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#f5c2e7',
})
vim.api.nvim_set_hl(0, 'CursorLine', {
  bg = '#45475a',
})
vim.api.nvim_set_hl(0, 'Search', {
  bg = '#74c7ec',
  fg = '#1e1e2e',
})
vim.api.nvim_set_hl(0, 'IncSearch', {
  bg = '#cba6f7',
  fg = '#1e1e2e',
})
vim.api.nvim_set_hl(0, 'PmenuSel', {
  bg = '#cba6f7',
  fg = '#1e1e2e',
})

-- Pmenu (needs bg to float above content)
vim.api.nvim_set_hl(0, 'Pmenu', {
  bg = '#45475a',
  fg = colors.fg,
})

-- StatusLine (needs bg to separate from content)
vim.api.nvim_set_hl(0, 'StatusLine', {
  bg = '#313244',
  fg = colors.fg,
})

-- Line numbers
vim.api.nvim_set_hl(0, 'LineNr', { fg = colors.comment })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = colors.primary, bold = true })

-- Comments
set_hl_multiple({ 'Comment', '@comment' }, {
  fg = colors.comment,
  italic = true,
})

-- Keywords (primary accent)
set_hl_multiple({ 'Keyword', '@keyword', '@keyword.control', '@keyword.function', 'Conditional', 'Repeat' }, {
  fg = colors.primary,
})

-- Functions (secondary accent)
set_hl_multiple({ 'Function', '@function', '@function.call', '@method', '@method.call' }, {
  fg = colors.secondary,
})

-- Strings (green)
set_hl_multiple({ 'String', '@string', '@string.escape' }, {
  fg = colors.green,
})

-- Numbers & Constants (orange)
set_hl_multiple({ 'Number', '@number', 'Boolean', '@boolean', 'Constant', '@constant' }, {
  fg = colors.orange,
})

-- Types & Classes (yellow)
set_hl_multiple({ 'Type', '@type', '@type.builtin', 'Structure', 'StorageClass' }, {
  fg = colors.yellow,
})

-- Variables (default fg)
set_hl_multiple({ 'Identifier', '@variable', '@parameter' }, {
  fg = colors.fg,
})

-- Special/Magic variables (red)
set_hl_multiple({ '@variable.builtin', 'Special' }, {
  fg = colors.red,
  italic = true,
})

-- Operators (fg)
set_hl_multiple({ 'Operator', '@operator' }, {
  fg = colors.cyan,
})

-- Punctuation
set_hl_multiple({ 'Delimiter', '@punctuation.delimiter', '@punctuation.bracket' }, {
  fg = colors.fg_dim,
})

-- Tags (HTML/XML)
set_hl_multiple({ 'Tag', '@tag', '@tag.delimiter' }, {
  fg = colors.primary,
})

-- Attributes
set_hl_multiple({ '@tag.attribute' }, {
  fg = colors.secondary,
  italic = true,
})

-- Diagnostics
vim.api.nvim_set_hl(0, 'Error', { fg = colors.red, bold = true })
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = colors.red })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = colors.yellow })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = colors.blue })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = colors.fg_dim })
