
$image = Null
$background = rgba(232136ff)

$image = Null
$error = rgba(eb6f92ff)

$image = Null
$error_container = rgba(eb6f92ff)

$image = Null
$inverse_on_surface = rgba(232136ff)

$image = Null
$inverse_primary = rgba(9ccfd8ff)

$image = Null
$inverse_surface = rgba(908caaff)

$image = Null
$on_background = rgba(e0def4ff)

$image = Null
$on_error = rgba(232136ff)

$image = Null
$on_error_container = rgba(232136ff)

$image = Null
$on_primary = rgba(232136ff)

$image = Null
$on_primary_container = rgba(232136ff)

$image = Null
$on_primary_fixed = rgba(232136ff)

$image = Null
$on_primary_fixed_variant = rgba(2a273fff)

$image = Null
$on_secondary = rgba(e0def4ff)

$image = Null
$on_secondary_container = rgba(232136ff)

$image = Null
$on_secondary_fixed = rgba(232136ff)

$image = Null
$on_secondary_fixed_variant = rgba(2a273fff)

$image = Null
$on_surface = rgba(e0def4ff)

$image = Null
$on_surface_variant = rgba(908caaff)

$image = Null
$on_tertiary = rgba(232136ff)

$image = Null
$on_tertiary_container = rgba(232136ff)

$image = Null
$on_tertiary_fixed = rgba(232136ff)

$image = Null
$on_tertiary_fixed_variant = rgba(2a273fff)

$image = Null
$outline = rgba(6e6a86ff)

$image = Null
$outline_variant = rgba(56526eff)

$image = Null
$primary = rgba(c4a7e7ff)

$image = Null
$primary_container = rgba(ea9a97ff)

$image = Null
$primary_fixed = rgba(ea9a97ff)

$image = Null
$primary_fixed_dim = rgba(c4a7e7ff)

$image = Null
$scrim = rgba(000000ff)

$image = Null
$secondary = rgba(3e8fb0ff)

$image = Null
$secondary_container = rgba(9ccfd8ff)

$image = Null
$secondary_fixed = rgba(9ccfd8ff)

$image = Null
$secondary_fixed_dim = rgba(3e8fb0ff)

$image = Null
$shadow = rgba(000000ff)

$image = Null
$source_color = rgba(c4a7e7ff)

$image = Null
$surface = rgba(232136ff)

$image = Null
$surface_bright = rgba(6e6a86ff)

$image = Null
$surface_container = rgba(2a283eff)

$image = Null
$surface_container_high = rgba(44415aff)

$image = Null
$surface_container_highest = rgba(56526eff)

$image = Null
$surface_container_low = rgba(2a273fff)

$image = Null
$surface_container_lowest = rgba(191724ff)

$image = Null
$surface_dim = rgba(232136ff)

$image = Null
$surface_tint = rgba(c4a7e7ff)

$image = Null
$surface_variant = rgba(56526eff)

$image = Null
$tertiary = rgba(f6c177ff)

$image = Null
$tertiary_container = rgba(ea9a97ff)

$image = Null
$tertiary_fixed = rgba(ea9a97ff)

$image = Null
$tertiary_fixed_dim = rgba(f6c177ff)
