cursor #e0def4
cursor_text_color #908caa

foreground            #e0def4
background            #191724
selection_foreground  #e0def4
selection_background  #3e8fb0
url_color             #c4a7e7

# black
color0   #44415a
color8   #56526e

# red (secondary, hue forced to red)
color1   #eb6f92
color9   #eb6f92

# green (tertiary, hue forced to green)
color2   #9ccfd8
color10  #9ccfd8

# yellow (primary, hue forced to yellow)
color3   #f6c177
color11  #f6c177

# blue (primary, as-is)
color4   #3e8fb0
color12  #3e8fb0

# magenta (secondary, hue forced to magenta)
color5   #c4a7e7
color13  #c4a7e7

# cyan (tertiary, hue forced to cyan)
color6   #9ccfd8
color14  #9ccfd8

# white
color7   #908caa
color15  #e0def4

mark1_foreground #232136
mark1_background #ea9a97
mark2_foreground #232136
mark2_background #9ccfd8
mark3_foreground #232136
mark3_background #ea9a97

active_tab_foreground #232136
active_tab_background #c4a7e7
inactive_tab_foreground #232136
inactive_tab_background #ea9a97

active_border_color #c4a7e7
inactive_border_color #232136
