[Metadata]
Name=noctalia
Version=1.0
Author=Kuroma
Description=noctalia theme for fcitx5

[InputPanel]
NormalColor={{colors.on_surface.default.hex}}
BackgroundColor={{colors.surface_container_high.default.hex}}
HighlightColor={{colors.primary.default.hex}}
HighlightCandidateColor={{colors.on_primary.default.hex}}
HighlightTextColor={{colors.on_surface.default.hex}}
CandidateTextColor={{colors.on_surface.default.hex}}
NormalTextColor={{colors.on_surface.default.hex}}
PreeditColor={{colors.on_surface.default.hex}}
AuxiliaryTextColor={{colors.on_surface.default.hex}}

[InputPanel/TextMargin]
Left=12
Right=12
Top=8
Bottom=8

[InputPanel/Background]
Color={{colors.surface_container_high.default.hex}}
BorderColor={{colors.primary.default.hex}}
BorderWidth=2

[InputPanel/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[InputPanel/Highlight]
Color={{colors.primary.default.hex}}

[InputPanel/Highlight/Margin]
Left=8
Right=8
Top=6
Bottom=6

[Menu]
NormalColor={{colors.surface_container_high.default.hex}}
HighlightColor={{colors.primary.default.hex}}
NormalTextColor={{colors.on_surface.default.hex}}
Spacing=4

[Menu/Background]
Color={{colors.surface_container_high.default.hex}}
BorderColor={{colors.primary.default.hex}}
BorderWidth=2

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/Highlight]
Color={{colors.primary.default.hex}}

[Menu/Separator]
Color={{colors.outline_variant.default.hex}}

[Menu/TextMargin]
Left=8
Right=8
Top=4
Bottom=4
