# Modified from End-4's animations
# credit https://github.com/end-4/dots-hyprland

animations {
    enabled = true
    bezier = fluent_decel, 0, 1, 0, 1
    bezier = quick, 0.15, 0, 0.1, 1
    animation = global, 1, 2, default
    animation = windows, 1, 2, fluent_decel, popin 80%
    animation = windowsIn, 1, 2, fluent_decel, popin 80%
    animation = windowsOut, 1, 2, quick, popin 80%
    animation = workspaces, 1, 2.5, fluent_decel, slidefade 15%
    animation = layersIn, 1, 1.5, fluent_decel, slidefade
    animation = layersOut, 1, 1.5, quick, slidefade
    animation = specialWorkspace, 1, 2, fluent_decel, slidevert
}

# SwayNC - slidefade from right
layerrule = animation slidefade right, match:namespace ^(swaync-control-center)$
# Walker, hyprpicker, selection - no animation
layerrule = no_anim on, match:namespace ^(walker)$
layerrule = no_anim on, match:namespace ^(hyprpicker)$
layerrule = no_anim on, match:namespace ^(selection)$