dwindle {
    pseudotile = true 
    preserve_split = true 
}

master {
    mfact = 0.48
    new_status = slave
}

scrolling {
    column_width = 1.0
    focus_fit_method = 0
    follow_focus = true
    follow_min_visible = 0.1
}

# default per-workspace layout
workspace = 1, layout:master # terminals
workspace = 5, layout:monocle
# second screen stuff
workspace = 11, layout:dwindle
workspace = 12, layout:dwindle
workspace = 13, layout:dwindle
workspace = 14, layout:dwindle
workspace = 15, layout:dwindle
workspace = 16, layout:dwindle
workspace = 17, layout:dwindle
workspace = 18, layout:dwindle
workspace = 19, layout:dwindle
workspace = 20, layout:dwindle