
$image = Null
$background = rgba(2d353bff)

$image = Null
$error = rgba(e67e80ff)

$image = Null
$error_container = rgba(e67e80ff)

$image = Null
$inverse_on_surface = rgba(2d353bff)

$image = Null
$inverse_primary = rgba(83c092ff)

$image = Null
$inverse_surface = rgba(859289ff)

$image = Null
$on_background = rgba(d3c6aaff)

$image = Null
$on_error = rgba(2d353bff)

$image = Null
$on_error_container = rgba(2d353bff)

$image = Null
$on_primary = rgba(2d353bff)

$image = Null
$on_primary_container = rgba(2d353bff)

$image = Null
$on_primary_fixed = rgba(2d353bff)

$image = Null
$on_primary_fixed_variant = rgba(3d484dff)

$image = Null
$on_secondary = rgba(2d353bff)

$image = Null
$on_secondary_container = rgba(2d353bff)

$image = Null
$on_secondary_fixed = rgba(2d353bff)

$image = Null
$on_secondary_fixed_variant = rgba(3d484dff)

$image = Null
$on_surface = rgba(d3c6aaff)

$image = Null
$on_surface_variant = rgba(9da9a0ff)

$image = Null
$on_tertiary = rgba(2d353bff)

$image = Null
$on_tertiary_container = rgba(2d353bff)

$image = Null
$on_tertiary_fixed = rgba(2d353bff)

$image = Null
$on_tertiary_fixed_variant = rgba(3d484dff)

$image = Null
$outline = rgba(7a8478ff)

$image = Null
$outline_variant = rgba(4f585eff)

$image = Null
$primary = rgba(a7c080ff)

$image = Null
$primary_container = rgba(83c092ff)

$image = Null
$primary_fixed = rgba(83c092ff)

$image = Null
$primary_fixed_dim = rgba(a7c080ff)

$image = Null
$scrim = rgba(000000ff)

$image = Null
$secondary = rgba(7fbbb3ff)

$image = Null
$secondary_container = rgba(d699b6ff)

$image = Null
$secondary_fixed = rgba(d699b6ff)

$image = Null
$secondary_fixed_dim = rgba(7fbbb3ff)

$image = Null
$shadow = rgba(000000ff)

$image = Null
$source_color = rgba(a7c080ff)

$image = Null
$surface = rgba(2d353bff)

$image = Null
$surface_bright = rgba(56635fff)

$image = Null
$surface_container = rgba(3d484dff)

$image = Null
$surface_container_high = rgba(475258ff)

$image = Null
$surface_container_highest = rgba(4f585eff)

$image = Null
$surface_container_low = rgba(343f44ff)

$image = Null
$surface_container_lowest = rgba(232a2eff)

$image = Null
$surface_dim = rgba(2d353bff)

$image = Null
$surface_tint = rgba(a7c080ff)

$image = Null
$surface_variant = rgba(4f585eff)

$image = Null
$tertiary = rgba(dbbc7fff)

$image = Null
$tertiary_container = rgba(e69875ff)

$image = Null
$tertiary_fixed = rgba(e69875ff)

$image = Null
$tertiary_fixed_dim = rgba(dbbc7fff)
