#!/usr/bin/env bash
set -euo pipefail

PYTHON=0; NPX=0; NETWORKING=0; CUDA=0; GIT=0
NAME=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --python)     PYTHON=1 ;;
    --npx)        NPX=1 ;;
    --networking) NETWORKING=1 ;;
    --cuda)       CUDA=1 ;;
    --git)        GIT=1 ;;
    --name)       shift; NAME="$1" ;;
    --name=*)     NAME="${1#--name=}" ;;
    --clean)
      TO_REMOVE=()
      [[ -f flake.nix ]]   && TO_REMOVE+=(flake.nix)
      [[ -f flake.lock ]]  && TO_REMOVE+=(flake.lock)
      if [[ -f .envrc ]] && grep -qx "use flake" .envrc 2>/dev/null; then
        TO_REMOVE+=(.envrc)
      fi
      [[ -d .direnv ]]        && TO_REMOVE+=(.direnv)
      [[ -d .venv ]]          && TO_REMOVE+=(.venv)
      [[ -f pyproject.toml ]] && TO_REMOVE+=(pyproject.toml)
      [[ -f uv.lock ]]        && TO_REMOVE+=(uv.lock)
      [[ -f hello.py ]]       && TO_REMOVE+=(hello.py)
      [[ -f main.py ]]        && TO_REMOVE+=(main.py)
      if [[ ${#TO_REMOVE[@]} -eq 0 ]]; then
        echo "Nothing to clean."
        exit 0
      fi
      echo "Will remove:"
      printf "  %s\n" "${TO_REMOVE[@]}"
      read -r -p "Confirm? [y/N] " REPLY
      [[ "$REPLY" =~ ^[Yy]$ ]] || { echo "Aborted."; exit 1; }
      rm -rf "${TO_REMOVE[@]}"
      echo "Done."
      exit 0 ;;
    --help|-h)
      cat << 'EOF'
Usage: init-shell [flags] [--name NAME]

Generates flake.nix + .envrc in the current directory.

  --python     Python dev tools (uv, ruff, black, pyright) — Python packages go in uv
  --cuda       CUDA libraries + LD_LIBRARY_PATH hook (independent of --python)
  --npx        Node.js / npx
  --networking Network/security tools (nmap, ffuf, gobuster, ...)
  --git        git init (if not already a repo) + .gitignore + git in devShell
  --name NAME  Shell name shown in starship prompt (default: directory name)
  --clean      Remove files generated by init-shell (flake.nix, .envrc, pyproject.toml, etc.)
  -h, --help   Show this help

TIP: Run in an empty project directory. Running in a large existing directory
causes nix flake lock to copy everything to the Nix store.
Use --git so Nix can filter via .gitignore instead.
EOF
      exit 0 ;;
    *) echo "Unknown flag: $1" >&2; exit 1 ;;
  esac
  shift
done

if [[ -f flake.nix ]]; then
  echo "flake.nix already exists. Aborting." >&2
  exit 1
fi

FILE_COUNT=$(find . -maxdepth 1 ! -name '.*' ! -name '.' | wc -l)
if [[ "$FILE_COUNT" -gt 50 ]]; then
  echo "Warning: $FILE_COUNT files in current directory." >&2
  echo "nix flake lock will copy all of them to the Nix store." >&2
  echo "Consider running in an empty subdirectory, or use --git so Nix filters via .gitignore." >&2
fi

SHELL_NAME="${NAME:-$(basename "$PWD")}"
# @NIXPKGS_REV@ is substituted at NixOS build time by apps.nix (builtins.replaceStrings),
# pinning generated flakes to the same nixpkgs rev the system was built with so
# package versions (Python, CUDA, etc.) stay in sync and don't unexpectedly update.
# ARCH is evaluated at runtime so the generated flake targets the current machine.
ARCH="$(uname -m)-linux"

PKGS=()
[[ $PYTHON -eq 1 ]]     && PKGS+=(python3 uv ruff black pyright)
[[ $NPX -eq 1 ]]        && PKGS+=(nodejs)
[[ $CUDA -eq 1 ]]       && PKGS+=(cudaPackages.cuda_cudart cudaPackages.libcublas cudaPackages.cuda_cccl)
[[ $NETWORKING -eq 1 ]] && PKGS+=(nmap masscan gobuster ffuf sqlmap nikto john hashcat hydra netcat-gnu wireshark tcpdump)
[[ $GIT -eq 1 ]]        && PKGS+=(git)

{
cat << HEADER
{
  description = "${SHELL_NAME}";
  inputs.nixpkgs.url = "github:nixos/nixpkgs/@NIXPKGS_REV@";
  outputs = { self, nixpkgs }:
  let
    pkgs = import nixpkgs { system = "${ARCH}"; config.allowUnfree = true; };
    lib = nixpkgs.lib;
  in {
    devShells.${ARCH}.default = pkgs.mkShell {
      packages = with pkgs; [
HEADER

for p in "${PKGS[@]}"; do printf "        %s\n" "$p"; done

cat << 'PKGSEND'
      ];
PKGSEND

printf '      DEV_SHELL = "%s";\n' "$SHELL_NAME"

if [[ $CUDA -eq 1 ]]; then
cat << 'CUDAENV'
      LD_LIBRARY_PATH = "/run/opengl-driver/lib:" + lib.makeLibraryPath (with pkgs; [ stdenv.cc.cc.lib zlib libGL cudaPackages.cuda_cudart cudaPackages.libcublas cudaPackages.cuda_cccl ]);
CUDAENV
elif [[ $PYTHON -eq 1 ]]; then
# stdenv.cc.cc.lib provides libstdc++.so.6 needed by uv-installed C extensions (numpy, torch, etc.)
cat << 'PYENV'
      LD_LIBRARY_PATH = lib.makeLibraryPath (with pkgs; [ stdenv.cc.cc.lib zlib ]);
PYENV
fi

cat << 'SHELLHOOK'
      shellHook = ''
SHELLHOOK

if [[ $PYTHON -eq 1 ]]; then
cat << 'VENV'
        if [ -d .venv ]; then
          export VIRTUAL_ENV="$PWD/.venv"
          export PATH="$PWD/.venv/bin:$PATH"
        fi
VENV
fi

cat << 'FOOTER'
        [[ $- == *i* ]] && exec zsh
      '';
    };
  };
}
FOOTER
} > flake.nix

if [[ $PYTHON -eq 1 ]]; then
  uv init --no-readme --no-workspace -q
  uv lock -q
fi

if [[ $GIT -eq 1 ]]; then
  if [[ -d .git ]]; then
    echo "Note: already a git repo — skipping git init."
  else
    git init -q
  fi
  if [[ ! -f .gitignore ]]; then
    cat > .gitignore << 'GITIGNORE'
.direnv/
.venv/
*.pyc
__pycache__/
node_modules/
result
GITIGNORE
  fi
fi

if [[ $PYTHON -eq 1 ]]; then
  mkdir -p .vscode
  if [[ ! -f .vscode/settings.json ]]; then
    cat > .vscode/settings.json << 'VSCODE'
{
  "python.defaultInterpreterPath": "${workspaceFolder}/.venv/bin/python"
}
VSCODE
  fi
fi

echo "use flake" > .envrc

if [[ $GIT -eq 1 ]]; then
  git add .
fi

# Allow before nix develop — a failed bootstrap can be retried without re-running direnv allow
direnv allow

if [[ $PYTHON -eq 1 ]]; then
  echo "Bootstrapping venv (fetches nixpkgs if not cached)..."
  nix develop --command bash -c "uv venv -q && uv pip install ipykernel -q"
  if [[ $GIT -eq 1 ]]; then
    git add flake.lock 2>/dev/null || true
  fi
fi

echo ""
echo "Shell '${SHELL_NAME}' ready."
echo "  Terminal : nix develop"
echo "  VSCodium : open folder (direnv loads PATH automatically)"
if [[ $PYTHON -eq 1 ]] && [[ $CUDA -eq 1 ]]; then
  echo ""
  echo "  PyTorch CUDA: uv add torch  (routes to CUDA index automatically)"
fi
