
$image = Null
$background = rgba(282828ff)

$image = Null
$error = rgba(cc241dff)

$image = Null
$error_container = rgba(fb4934ff)

$image = Null
$inverse_on_surface = rgba(282828ff)

$image = Null
$inverse_primary = rgba(fabd2fff)

$image = Null
$inverse_surface = rgba(a89984ff)

$image = Null
$on_background = rgba(fbf1c7ff)

$image = Null
$on_error = rgba(282828ff)

$image = Null
$on_error_container = rgba(282828ff)

$image = Null
$on_primary = rgba(282828ff)

$image = Null
$on_primary_container = rgba(282828ff)

$image = Null
$on_primary_fixed = rgba(282828ff)

$image = Null
$on_primary_fixed_variant = rgba(3c3836ff)

$image = Null
$on_secondary = rgba(282828ff)

$image = Null
$on_secondary_container = rgba(282828ff)

$image = Null
$on_secondary_fixed = rgba(282828ff)

$image = Null
$on_secondary_fixed_variant = rgba(3c3836ff)

$image = Null
$on_surface = rgba(ebdbb2ff)

$image = Null
$on_surface_variant = rgba(d5c4a1ff)

$image = Null
$on_tertiary = rgba(282828ff)

$image = Null
$on_tertiary_container = rgba(282828ff)

$image = Null
$on_tertiary_fixed = rgba(282828ff)

$image = Null
$on_tertiary_fixed_variant = rgba(3c3836ff)

$image = Null
$outline = rgba(928374ff)

$image = Null
$outline_variant = rgba(665c54ff)

$image = Null
$primary = rgba(d79921ff)

$image = Null
$primary_container = rgba(fabd2fff)

$image = Null
$primary_fixed = rgba(fabd2fff)

$image = Null
$primary_fixed_dim = rgba(d79921ff)

$image = Null
$scrim = rgba(000000ff)

$image = Null
$secondary = rgba(458588ff)

$image = Null
$secondary_container = rgba(83a598ff)

$image = Null
$secondary_fixed = rgba(83a598ff)

$image = Null
$secondary_fixed_dim = rgba(458588ff)

$image = Null
$shadow = rgba(000000ff)

$image = Null
$source_color = rgba(d79921ff)

$image = Null
$surface = rgba(282828ff)

$image = Null
$surface_bright = rgba(7c6f64ff)

$image = Null
$surface_container = rgba(3c3836ff)

$image = Null
$surface_container_high = rgba(504945ff)

$image = Null
$surface_container_highest = rgba(665c54ff)

$image = Null
$surface_container_low = rgba(32302fff)

$image = Null
$surface_container_lowest = rgba(1d2021ff)

$image = Null
$surface_dim = rgba(282828ff)

$image = Null
$surface_tint = rgba(d79921ff)

$image = Null
$surface_variant = rgba(504945ff)

$image = Null
$tertiary = rgba(689d6aff)

$image = Null
$tertiary_container = rgba(8ec07cff)

$image = Null
$tertiary_fixed = rgba(8ec07cff)

$image = Null
$tertiary_fixed_dim = rgba(689d6aff)
