cursor #ebdbb2
cursor_text_color #d5c4a1

foreground            #ebdbb2
background            #1d2021
selection_foreground  #282828
selection_background  #458588
url_color             #d79921

# black
color0   #504945
color8   #665c54

# red (secondary, hue forced to red)
color1   #cc241d
color9   #fb4934

# green (tertiary, hue forced to green)
color2   #98971a
color10  #b8bb26

# yellow (primary, hue forced to yellow)
color3   #d79921
color11  #fabd2f

# blue (primary, as-is)
color4   #458588
color12  #83a598

# magenta (secondary, hue forced to magenta)
color5   #b16286
color13  #d3869b

# cyan (tertiary, hue forced to cyan)
color6   #689d6a
color14  #8ec07c

# white
color7   #a89984
color15  #fbf1c7

mark1_foreground #282828
mark1_background #fabd2f
mark2_foreground #282828
mark2_background #83a598
mark3_foreground #282828
mark3_background #8ec07c

active_tab_foreground #282828
active_tab_background #d79921
inactive_tab_foreground #282828
inactive_tab_background #fabd2f

active_border_color #d79921
inactive_border_color #282828
