cursor {{colors.on_surface.default.hex}}
cursor_text_color {{colors.on_surface_variant.default.hex}}

foreground            {{colors.on_surface.default.hex}}
background            {{colors.surface_container_lowest.default.hex}}
selection_foreground  {{colors.on_secondary.default.hex}}
selection_background  {{colors.secondary_fixed_dim.default.hex}}
url_color             {{colors.primary.default.hex}}

# black
color0   {{colors.surface_container_high.default.hex}}
color8   {{colors.surface_container_highest.default.hex}}

# red (secondary, hue forced to red)
color1   {{colors.primary.default.hex | set_hue: 0 | lighten: -10}}
color9   {{colors.secondary.default.hex | set_hue: 0 | lighten: -10}}

# green (tertiary, hue forced to green)
color2   {{colors.primary.default.hex | set_hue: 120}}
color10  {{colors.secondary.default.hex | set_hue: 120}}

# yellow (primary, hue forced to yellow)
color3   {{colors.primary.default.hex | set_hue: 60}}
color11  {{colors.secondary.default.hex | set_hue: 60}}

# blue (primary, as-is)
color4   {{colors.primary.default.hex}}
color12  {{colors.primary.default.hex}}

# magenta (secondary, hue forced to magenta)
color5   {{colors.primary.default.hex | set_hue: 300}}
color13  {{colors.secondary.default.hex | set_hue: 300}}

# cyan (tertiary, hue forced to cyan)
color6   {{colors.primary.default.hex | set_hue: 180}}
color14  {{colors.secondary.default.hex | set_hue: 180}}

# white
color7   {{colors.inverse_surface.default.hex}}
color15  {{colors.on_background.default.hex}}

mark1_foreground {{ colors.on_primary_fixed.dark.hex }}
mark1_background {{ colors.primary_fixed.dark.hex }}
mark2_foreground {{ colors.on_secondary_fixed.dark.hex }}
mark2_background {{ colors.secondary_fixed.dark.hex }}
mark3_foreground {{ colors.on_tertiary_fixed.dark.hex }}
mark3_background {{ colors.tertiary_fixed.dark.hex }}

active_tab_foreground {{ colors.on_primary.dark.hex }}
active_tab_background {{ colors.primary.dark.hex }}
inactive_tab_foreground {{ colors.on_primary_container.dark.hex }}
inactive_tab_background {{ colors.primary_container.dark.hex }}

active_border_color {{ colors.primary.dark.hex }}
inactive_border_color {{ colors.on_primary.dark.hex }}
