-- Auto-generated by Matugen
-- Colors derived from matugen palette with forced hues (matching ANSI/kitty)

local colors = {
  red      = '{{colors.primary.default.hex | set_hue: 0}}',
  green    = '{{colors.primary.default.hex | set_hue: 120}}',
  yellow   = '{{colors.primary.default.hex | set_hue: 60}}',
  blue     = '{{colors.primary.default.hex | set_hue: 240}}',
  magenta  = '{{colors.primary.default.hex | set_hue: 300}}',
  cyan     = '{{colors.primary.default.hex | set_hue: 180}}',
  orange   = '{{colors.primary.default.hex | set_hue: 30}}',
  pink     = '{{colors.primary.default.hex | set_hue: 330}}',

  fg       = '{{colors.on_surface.default.hex}}',
  fg_dim   = '{{colors.on_surface_variant.default.hex}}',
  comment  = '{{colors.outline.default.hex}}',
  primary  = '{{colors.primary.default.hex}}',
  secondary = '{{colors.secondary.default.hex}}',
}

-- Helper
local function set_hl_multiple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Core: transparent backgrounds
vim.api.nvim_set_hl(0, 'Normal', { fg = colors.fg, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'NormalNC', { fg = colors.fg, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'NormalFloat', { fg = colors.fg, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'SignColumn', { bg = 'NONE' })
vim.api.nvim_set_hl(0, 'EndOfBuffer', { fg = colors.comment, bg = 'NONE' })
vim.api.nvim_set_hl(0, 'MsgArea', { fg = colors.fg, bg = 'NONE' })

-- Selection / cursor (these need bg to be readable)
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '{{colors.primary_container.default.hex}}',
})
vim.api.nvim_set_hl(0, 'CursorLine', {
  bg = '{{colors.surface_container_high.default.hex}}',
})
vim.api.nvim_set_hl(0, 'Search', {
  bg = '{{colors.secondary_container.default.hex}}',
  fg = '{{colors.on_secondary_container.default.hex}}',
})
vim.api.nvim_set_hl(0, 'IncSearch', {
  bg = '{{colors.primary.default.hex}}',
  fg = '{{colors.on_primary.default.hex}}',
})
vim.api.nvim_set_hl(0, 'PmenuSel', {
  bg = '{{colors.primary.default.hex}}',
  fg = '{{colors.on_primary.default.hex}}',
})

-- Pmenu (needs bg to float above content)
vim.api.nvim_set_hl(0, 'Pmenu', {
  bg = '{{colors.surface_container_high.default.hex}}',
  fg = colors.fg,
})

-- StatusLine (needs bg to separate from content)
vim.api.nvim_set_hl(0, 'StatusLine', {
  bg = '{{colors.surface_container.default.hex}}',
  fg = colors.fg,
})

-- Line numbers
vim.api.nvim_set_hl(0, 'LineNr', { fg = colors.comment })
vim.api.nvim_set_hl(0, 'CursorLineNr', { fg = colors.primary, bold = true })

-- Comments
set_hl_multiple({ 'Comment', '@comment' }, {
  fg = colors.comment,
  italic = true,
})

-- Keywords (primary accent)
set_hl_multiple({ 'Keyword', '@keyword', '@keyword.control', '@keyword.function', 'Conditional', 'Repeat' }, {
  fg = colors.primary,
})

-- Functions (secondary accent)
set_hl_multiple({ 'Function', '@function', '@function.call', '@method', '@method.call' }, {
  fg = colors.secondary,
})

-- Strings (green)
set_hl_multiple({ 'String', '@string', '@string.escape' }, {
  fg = colors.green,
})

-- Numbers & Constants (orange)
set_hl_multiple({ 'Number', '@number', 'Boolean', '@boolean', 'Constant', '@constant' }, {
  fg = colors.orange,
})

-- Types & Classes (yellow)
set_hl_multiple({ 'Type', '@type', '@type.builtin', 'Structure', 'StorageClass' }, {
  fg = colors.yellow,
})

-- Variables (default fg)
set_hl_multiple({ 'Identifier', '@variable', '@parameter' }, {
  fg = colors.fg,
})

-- Special/Magic variables (red)
set_hl_multiple({ '@variable.builtin', 'Special' }, {
  fg = colors.red,
  italic = true,
})

-- Operators (fg)
set_hl_multiple({ 'Operator', '@operator' }, {
  fg = colors.cyan,
})

-- Punctuation
set_hl_multiple({ 'Delimiter', '@punctuation.delimiter', '@punctuation.bracket' }, {
  fg = colors.fg_dim,
})

-- Tags (HTML/XML)
set_hl_multiple({ 'Tag', '@tag', '@tag.delimiter' }, {
  fg = colors.primary,
})

-- Attributes
set_hl_multiple({ '@tag.attribute' }, {
  fg = colors.secondary,
  italic = true,
})

-- Diagnostics
vim.api.nvim_set_hl(0, 'Error', { fg = colors.red, bold = true })
vim.api.nvim_set_hl(0, 'DiagnosticError', { fg = colors.red })
vim.api.nvim_set_hl(0, 'DiagnosticWarn', { fg = colors.yellow })
vim.api.nvim_set_hl(0, 'DiagnosticInfo', { fg = colors.blue })
vim.api.nvim_set_hl(0, 'DiagnosticHint', { fg = colors.fg_dim })
